<a href="https://colab.research.google.com/github/swarnim288/swarnimjainACM/blob/main/q1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
import pandas as pd
import matplotlib as mt


print numpy configuration

In [6]:
x=np.show_config()
print(x)

openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None

initialize a vector containing numbers from 1 to 20


In [7]:
numbers = np.arange(1,21)
print(numbers)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


reversing the vector


In [8]:
reversed_numbers =np.flip(numbers)
print(reversed_numbers)

[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


create a 3*3 array with random values and find the maximum and minimum values

In [9]:
array=np.random.randint(0,100,size=(3,3))
print(array)
min=array.min()
max=array.max()
print(f"maximum value is {max}")
print(f"minimum value is {min}")


[[19 90 85]
 [89 79 92]
 [32 16 99]]
maximum value is 99
minimum value is 16


(5,5,8) array and its 100th element

In [14]:
index=np.unravel_index(100,(5,5,8))
print(f"\n index of 100th element{index}")


 index of 100th element(2, 2, 4)


finding common values between two arrays

In [10]:
#declare two arrays
array1=np.array([1,2,3,4,5])
array2=np.array([3,4,5,6,7,8,9])
common_values=np.intersect1d(array1,array2)
print(f"commmon values are{common_values}")

commmon values are[3 4 5]


to find the common element of 2d or 3d arrays we first need to flatten the arrays usingflatten() attribute

consider a random 10*2 matrix representing cartresian coordinates and converting them to polar  coordinates

In [13]:
cartesian = np.random.rand(10,2)
x=cartesian[:,0]
y=cartesian[:,1]
radius=np.sqrt(x**2 + y**2)
angle_radians=np.arctan2(y,x)
angle_degrees=np.degrees(angle_radians)
polar=np.column_stack((radius,angle_degrees))
print(f"cartesian coordinates is {cartesian}")
print(f"\n  polar coordinatesian {polar}")

cartesian coordinates is [[0.27809347 0.41554177]
 [0.62325116 0.59268774]
 [0.04152188 0.48656132]
 [0.10307827 0.25844808]
 [0.41435635 0.19678291]
 [0.27343774 0.24821962]
 [0.96787616 0.82640777]
 [0.09731208 0.82015867]
 [0.98341435 0.59724639]
 [0.284707   0.26547902]]

  polar coordinatesian [[ 0.50001094 56.20833119]
 [ 0.86007021 43.56013632]
 [ 0.48832979 85.12234425]
 [ 0.27824547 68.25613055]
 [ 0.45870982 25.40361551]
 [ 0.36929822 42.23234454]
 [ 1.27268773 40.4919019 ]
 [ 0.82591155 83.23347241]
 [ 1.15056813 31.27111243]
 [ 0.38927778 42.99843312]]


demonstration of printing all values of array

In [12]:
arrayq=np.array([[1,2,3],[4,5,6],[7,8,9]])
rows, cols = arrayq.shape
for i in range(rows):
  for j in range(cols):
    print(arrayq[i,j])

1
2
3
4
5
6
7
8
9


coverting float array into integer array

In [15]:
float_array=np.array([1.1,2.2,3.3,44.4], dtype=np.float32)
int_array=float_array.view(dtype=np.int32)
print("converted integer arrayis")
print(int_array)

converted integer arrayis
[1066192077 1074580685 1079194419 1110546842]
